#ifndef __STM32_LTDC_PINS_H__
#define __STM32_LTDC_PINS_H__

// LCD Pins.
#define LCD_DISP_Pin          GPIO_PIN_12
#define LCD_BL_CTRL_Pin       GPIO_PIN_3
#define LCD_BL_CTRL_GPIO_Port GPIOK
#define LCD_DISP_GPIO_Port    GPIOI
#define LCD_VSYNC_Pin         GPIO_PIN_9
#define LCD_VSYNC_GPIO_Port   GPIOI
#define LCD_HSYNC_Pin         GPIO_PIN_10
#define LCD_HSYNC_GPIO_Port   GPIOI
#define LCD_CLK_Pin           GPIO_PIN_14
#define LCD_CLK_GPIO_Port     GPIOI
#define LCD_DE_Pin            GPIO_PIN_7
#define LCD_DE_GPIO_Port      GPIOK
#define LCD_R0_Pin            GPIO_PIN_15
#define LCD_R0_GPIO_Port      GPIOI
#define LCD_R1_Pin            GPIO_PIN_0
#define LCD_R1_GPIO_Port      GPIOJ
#define LCD_R2_Pin            GPIO_PIN_1
#define LCD_R2_GPIO_Port      GPIOJ
#define LCD_R3_Pin            GPIO_PIN_2
#define LCD_R3_GPIO_Port      GPIOJ
#define LCD_R4_Pin            GPIO_PIN_3
#define LCD_R4_GPIO_Port      GPIOJ
#define LCD_R5_Pin            GPIO_PIN_4
#define LCD_R5_GPIO_Port      GPIOJ
#define LCD_R6_Pin            GPIO_PIN_5
#define LCD_R6_GPIO_Port      GPIOJ
#define LCD_R7_Pin            GPIO_PIN_6
#define LCD_R7_GPIO_Port      GPIOJ
#define LCD_G0_Pin            GPIO_PIN_7
#define LCD_G0_GPIO_Port      GPIOJ
#define LCD_G1_Pin            GPIO_PIN_8
#define LCD_G1_GPIO_Port      GPIOJ
#define LCD_G2_Pin            GPIO_PIN_9
#define LCD_G2_GPIO_Port      GPIOJ
#define LCD_G3_Pin            GPIO_PIN_10
#define LCD_G3_GPIO_Port      GPIOJ
#define LCD_G4_Pin            GPIO_PIN_11
#define LCD_G4_GPIO_Port      GPIOJ
#define LCD_G5_Pin            GPIO_PIN_0
#define LCD_G5_GPIO_Port      GPIOK
#define LCD_G6_Pin            GPIO_PIN_1
#define LCD_G6_GPIO_Port      GPIOK
#define LCD_G7_Pin            GPIO_PIN_2
#define LCD_G7_GPIO_Port      GPIOK
#define LCD_B0_Pin            GPIO_PIN_4
#define LCD_B0_GPIO_Port      GPIOE
#define LCD_B1_Pin            GPIO_PIN_13
#define LCD_B1_GPIO_Port      GPIOJ
#define LCD_B2_Pin            GPIO_PIN_14
#define LCD_B2_GPIO_Port      GPIOJ
#define LCD_B3_Pin            GPIO_PIN_15
#define LCD_B3_GPIO_Port      GPIOJ
#define LCD_B4_Pin            GPIO_PIN_12
#define LCD_B4_GPIO_Port      GPIOG
#define LCD_B5_Pin            GPIO_PIN_4
#define LCD_B5_GPIO_Port      GPIOK
#define LCD_B6_Pin            GPIO_PIN_5
#define LCD_B6_GPIO_Port      GPIOK
#define LCD_B7_Pin            GPIO_PIN_6
#define LCD_B7_GPIO_Port      GPIOK

// SDRAM Pins.
#define FMC_BA1_Pin          GPIO_PIN_5
#define FMC_BA1_GPIO_Port    GPIOG
#define FMC_BA0_Pin          GPIO_PIN_4
#define FMC_BA0_GPIO_Port    GPIOG
#define FMC_SDNRAS_Pin       GPIO_PIN_11
#define FMC_SDNRAS_GPIO_Port GPIOF
#define FMC_SDCLK_Pin        GPIO_PIN_8
#define FMC_SDCLK_GPIO_Port  GPIOG
#define FMC_SDNME_Pin        GPIO_PIN_5
#define FMC_SDNME_GPIO_Port  GPIOH
#define FMC_SDNE0_Pin        GPIO_PIN_3
#define FMC_SDNE0_GPIO_Port  GPIOH
#define FMC_SDCKE0_Pin       GPIO_PIN_3
#define FMC_SDCKE0_GPIO_Port GPIOC
#define FMC_NBL1_Pin         GPIO_PIN_1
#define FMC_NBL1_GPIO_Port   GPIOE
#define FMC_NBL0_Pin         GPIO_PIN_0
#define FMC_NBL0_GPIO_Port   GPIOE
#define FMC_SDNCAS_Pin       GPIO_PIN_15
#define FMC_SDNCAS_GPIO_Port GPIOG
#define FMC_D0_Pin           GPIO_PIN_14
#define FMC_D0_GPIO_Port     GPIOD
#define FMC_D1_Pin           GPIO_PIN_15
#define FMC_D1_GPIO_Port     GPIOD
#define FMC_D2_Pin           GPIO_PIN_0
#define FMC_D2_GPIO_Port     GPIOD
#define FMC_D3_Pin           GPIO_PIN_1
#define FMC_D3_GPIO_Port     GPIOD
#define FMC_D4_Pin           GPIO_PIN_7
#define FMC_D4_GPIO_Port     GPIOE
#define FMC_D5_Pin           GPIO_PIN_8
#define FMC_D5_GPIO_Port     GPIOE
#define FMC_D6_Pin           GPIO_PIN_9
#define FMC_D6_GPIO_Port     GPIOE
#define FMC_D7_Pin           GPIO_PIN_10
#define FMC_D7_GPIO_Port     GPIOE
#define FMC_D8_Pin           GPIO_PIN_11
#define FMC_D8_GPIO_Port     GPIOE
#define FMC_D9_Pin           GPIO_PIN_12
#define FMC_D9_GPIO_Port     GPIOE
#define FMC_D10_Pin          GPIO_PIN_13
#define FMC_D10_GPIO_Port    GPIOE
#define FMC_D11_Pin          GPIO_PIN_14
#define FMC_D11_GPIO_Port    GPIOE
#define FMC_D12_Pin          GPIO_PIN_15
#define FMC_D12_GPIO_Port    GPIOE
#define FMC_D13_Pin          GPIO_PIN_8
#define FMC_D13_GPIO_Port    GPIOD
#define FMC_D14_Pin          GPIO_PIN_9
#define FMC_D14_GPIO_Port    GPIOD
#define FMC_D15_Pin          GPIO_PIN_10
#define FMC_D15_GPIO_Port    GPIOD
#define FMC_A0_Pin           GPIO_PIN_0
#define FMC_A0_GPIO_Port     GPIOF
#define FMC_A1_Pin           GPIO_PIN_1
#define FMC_A1_GPIO_Port     GPIOF
#define FMC_A2_Pin           GPIO_PIN_2
#define FMC_A2_GPIO_Port     GPIOF
#define FMC_A3_Pin           GPIO_PIN_3
#define FMC_A3_GPIO_Port     GPIOF
#define FMC_A4_Pin           GPIO_PIN_4
#define FMC_A4_GPIO_Port     GPIOF
#define FMC_A5_Pin           GPIO_PIN_5
#define FMC_A5_GPIO_Port     GPIOF
#define FMC_A6_Pin           GPIO_PIN_12
#define FMC_A6_GPIO_Port     GPIOF
#define FMC_A7_Pin           GPIO_PIN_13
#define FMC_A7_GPIO_Port     GPIOF
#define FMC_A8_Pin           GPIO_PIN_14
#define FMC_A8_GPIO_Port     GPIOF
#define FMC_A9_Pin           GPIO_PIN_15
#define FMC_A9_GPIO_Port     GPIOF
#define FMC_A10_Pin          GPIO_PIN_0
#define FMC_A10_GPIO_Port    GPIOG
#define FMC_A11_Pin          GPIO_PIN_1
#define FMC_A11_GPIO_Port    GPIOG

#endif